<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAIoLGwf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAIoLGwf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAIoLGwf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAIoLGwf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAIoLGwf\App_KernelDevDebugContainer([
    'container.build_hash' => 'AIoLGwf',
    'container.build_id' => '93c98aa2',
    'container.build_time' => 1590694420,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAIoLGwf');
